### ISSUE TITLE
Can't authorize our application on some devices.

### ISSUE THREAD

**Issue by rz-robsn** [uber/rides-android-sdk#58]
Hi,

At my company, we are getting some errors while trying to authenticate using SSO. The weird thing is this error occurs only on some of our devices and not others. 

More specifically, the activity provided by the uber app that handles the authorization always finishes immediately after being started. When it finishes, the bundle that it sends as a result  contains sometimes {"ERROR": "unavailable"}, and some other times {"ERROR": "expired_jwt"}.

We seem to be able to reproduce this bug only on a handful of our devices :
- An LG Nexus 4 running Android 5.1.1
- A Samsung Galaxy S4 running Android 4.4.2

The problem can be reproduced using the login-sample app, and it seems it only happens when you request a privileged scope. In the sample app, if you tap on the button "sign in" button to the top or the "I want to sign in using my uber app" button at the bottom, your are shown the Uber login screen. However if you tap on the "sign in" button in the middle (which requests the _request_ scope upon sign in), the problem that I've specified above occurs. 

This is the code the we currently use to setup to login with uber sdk :

```
// in our application's OnCreate
SessionConfiguration config = new SessionConfiguration.Builder()
               .setClientId(UBER_CLIENT_ID)
               .setEnvironment(SessionConfiguration.Environment.SANDBOX)
               .setScopes(
                     Arrays.asList(Scope.PLACES, Scope.HISTORY,
                           Scope.REQUEST, Scope.REQUEST_RECEIPT))
               .build();
UberSdk.initialize(config);

...

// when the user requests to login
loginManager.login(activity);
```

We could reproduce the issue on the sandbox as well as on the production environment. Our application has already been granted full access.

The problem still occurs after a complete reinstall of both our app and the uber app.

The version of the uber application that we have installed is 3.123.2

Thank you in advance for your help, let me know if you need any more info.

**Comment by itstexter** [comment]
Wow thank you for the very detailed post! We'll look into this with more
detail, but some initial reactions based on what you posted...

In the case where it's asking for non privileged scopes, does it actually
deeplink into the Uber app, or does it present you with a username and
password flow? If it's the latter, then it's actually Implicit Grant that's
working and not SSO. If that's the case, it sounds like you've never
successfully gotten an access token through SSO.

If that's the case, there's a couple of issues I can think of,
unfortunately INVALID_JWT and UNAVAILABLE are two of our catch all, less
detailed errors. If you're doing a lot of signing in and signing out of the
Uber app (or uninstalling) while trying to use SSO, that might be what's
causing the INVALID_JWT exception, but it shouldn't be permanent and it
sounds like you haven't been able to get a token yet... Are you doing
anything particular about how you sign your application? That's another
possible cause of INVALID_JWT, if the application signature isn't
consistent the whole way down.

Just some initial thoughts on it, I'll look into what you were saying more.
Please let me know if it's that you're able to get the token through
Implicit Grant (you have to enter your username and password) or SSO
(deeplinks into the Uber app, no username or password entry necessary).

**Comment by rz-robsn** [comment]
Thanks for the quick response, @itstexter !

> In the case where it's asking for non privileged scopes, does it actually
deeplink into the Uber app, or does it present you with a username and
password flow?

It presents me with a username and password flow. So you're right, it's not actually SSO.

> If you're doing a lot of signing in and signing out of the
Uber app (or uninstalling) while trying to use SSO, that might be what's
causing the INVALID_JWT exception.

The error that we get is not INVALID_JWT but EXPIRED_JWT. Also I'm not sure if the problem is related to the fact that we are trying to sign in and out because we were never able to log in using those devices, and I have uninstalled both uber and our application multiple times.

> Are you doing anything particular about how you sign your application ?

I'm not sure about that... I'll have to get back to you on that.

> Please let me know if it's that you're able to get the token through
Implicit Grant or SSO

I can login just fine using the implicit grant, but not using SSO.

**Comment by itstexter** [comment]
Hey @rz-robsn!

So sorry for misreading the error as INVALID_JWT, my bad! If you're consistently getting EXPIRED_JWT the error is much clearer. For security purposes we expire your login attempt if it takes over 30 seconds. If your device's system clock is over 30 seconds off the current unix time, or loading the web page is taking over 30 seconds, then you'll get an EXPIRED_JWT error, try checking those device's current UNIX time.

If you're getting UNAVAILABLE and it's based around logging in and out I'm realizing that it might be because SSO is currently behind a feature flag, so try logging in and waiting several minutes for the flags to be downloaded and SSO can be done. This will be fixed in an upcoming update to the Uber App, but it would be the most obvious thing I can think of for the UNAVAILABLE.

**Comment by rz-robsn** [comment]
> try checking those device's current UNIX time.

I checked the time on the devices. The Samsung Galaxy S4 was actually about 2 mins behind the actual time and the LG Nexus 4 was actually about 1 min behind.

I systematically got EXPIRED_JWT error on the S4 and the UNAVAILABLE error on the Nexus 4.

Synchronizing the clock with the network's on the S4 fixed the EXPIRED_JWT issue ! Now I can properly authorize the application on that device. Thank you for your help !

However, I still have the UNAVAILABLE error on the Nexus 4, even after synchronizing the device's clock.

> try logging in and waiting several minutes for the flags to be downloaded and SSO can be done.

I have logged in the uber app, waited a few hours, then tried logging with SSO from the login-sample app. I still get the UNAVAILABLE error :-( ...

**Comment by itstexter** [comment]
Glad we were able to figure out the EXPIRED_JWT issue!

Consistently getting unavailable is definitely strange. I know you mentioned it before but I just wanted to confirm, both the S4 and the Nexus 4 are on the Uber app version 3.123.2?

**Comment by rz-robsn** [comment]
Hi @itstexter,

The Nexus 4 and the S4 had Uber 3.123.2 installed when I reported the problem 2 days ago.

Yesterday, both devices automatically updated Uber to 3.124.2. I still have the UNAVAILABLE error on the Nexus 4 on this version too, even after a fresh reinstall of both uber and the login-sample app (and logging into uber and wait several minutes before trying to authorize with SSO).

**Comment by rz-robsn** [comment]
On a related note, about the EXPIRED_JWT issue, we are thinking about inviting the user to try to update its device clock in case we are receiving this error while trying to authorize. 

Could you tell us if we could get that error code in cases other than the 30 seconds login expiry attempt ? The current code documentation is quite terse about this :

```
// AuthenticationError.java

    /**
     * JWT TTL has expired.
     */
    EXPIRED_JWT,
```

**Comment by itstexter** [comment]
The only two cases that I can think of that that would cause that to occur:

A. The device clock is off.

B. The page took over 30 seconds to load.

I'd say it's probably reasonable ask to have them update their device clock either way. I should look into our analytics on this and if it's happening quite a bit building it into the SDK might be a good idea.

Still looking into the UNAVAILABLE bit, testing some things locally on it, sorry! Will ping here when I have other ideas...

**Comment by rz-robsn** [comment]
Hey @itstexter, 

I have accidentally found a workaround about the UNAVAILABLE error on the LG G4. When you try to login after a device reboot the problem disappears !

However if I uninstall and reinstall Uber again afterwards, I still get the UNAVAILABLE error systematically until I reboot the device.

It looks like the SSO attempt will fail if the user has not rebooted his device between the installation of the Uber app and the SSO login attempt, strange...

By the way, the version of Uber that I have installed on the LG G4 is now 3.125.1

**Comment by Csaba8472** [comment]
hi

same problem here on a oneplus3(6.0.1), nexus 6p(7.0) and on a s6 edge. The workaround works, but my app is in production so I really don't want my users to restart their phones :) . When will you fix it?

Thanks!

**Comment by itstexter** [comment]
Thanks for all the info and updates @rz-robsn and @Csaba8472. We'll be fixing this in an update to the Uber App, I'll ping this thread when that's rolling out.

**Comment by Csaba8472** [comment]
guess today's update wasn't _that_ update...

**Comment by itstexter** [comment]
Actually, we do believe this should be fixed in the new Uber App! However it is rolled out gradually and is not available to all users yet, so I was going to wait to close this issue.

I guess I'll just say that it should be fixed once the new app rolls out to you. Would you mind pinging this thread and confirming the old problem no longer exists with the new Uber App @rz-robsn and @Csaba8472 ? Once I've confirmed that I'll close this issue.

**Comment by Csaba8472** [comment]
I updated today,  the version number is: 3.127.1(4289AF8). Is this the new version?

**Comment by rz-robsn** [comment]
Hi @itstexter,

I still have the same UNAVAILABLE problem on version 3.127.1 using the login-sample app on the LG G4. I uninstalled/reinstalled both apps and I still have the same issue.

Rebooting the device still works as a workaround.

**Comment by itstexter** [comment]
Are you on the new form of the app though? It's only rolled out to a subset
of our users so if you don't have the new app and just have the latest
version of the old app then the bug still remains. If you don't have the
one that opens with a "Where to?" Bar at the top the new app hasn't been
rolled out to you.

**Comment by rz-robsn** [comment]
I see, I don't have the the new Uber App installed on the device, so that explains why the problem still occurs.

**Comment by Csaba8472** [comment]
@itstexter could you give us specific version number?

**Comment by Csaba8472** [comment]
Uber was updated on November 3 and still doesn't work... I'm getting negative reviews because I said it's going to be fixed in the next update. What should I say them?

**Comment by itstexter** [comment]
Sorry @Csaba8472 I've been having trouble figuring out if there is a specific version I can give you. Since we've wrapped both apps into one deliverable you may have the same app version but the new app not yet delivered to you. The best indicator of whether or not you have the new App is if you boot it up does it have the new look and "Where to?" destination field.

As the new app is rolled out over the following weeks more users will be getting access, so once it's fully rolled out SSO users shouldn't be seeing the UNAVAILABLE issue.

**Comment by tyvsmith** [comment]
@Csaba8472 Sorry for your troubles here. 

We have released the [new rider app](https://newsroom.uber.com/newriderapp/) which should systematically address this issue. As it incrementally rolls out over the next few weeks, this will be no longer be an issue. I'll close this thread for now, but please re-open if there are any issues post receiving the new app.
